config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_for :users
  root to: 'pages#home'
  get "pages/plug" => "pages#plug"
  get "pages/podcast" => "pages#podcast"
  get "pages/about" => "pages#about"
  get "pages/pace" => "pages#pace"
  # get "pages/dashboard" => "pages#dashboard"
  get "/youtube_sessions" => "youtube_sessions#new"
  get "/youtube_sessions/callback" => "youtube_sessions#callback"

  # get "pages/rankings" => "pages#rankings"
  resources :rankings
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :photo, presence: true

  has_one_attached :photo
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :rankings, dependent: :destroy
end

app/models/youtube_session.rb
class YoutubeSession < ApplicationRecord
  before_validation(on: :create) do
    self.session_token ||= SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
   include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :set_latest_blog, only: %i[index show]
  def index
    @blogs = policy_scope(Blog).order(created_at: :desc)
    # search bar
    if params[:query].present?
      sql_query = " \
        blogs.title @@ :query \
        OR blogs.body @@ :query \
        OR blogs.subject @@ :query \
      "
      @blogs = Blog.where(sql_query, query: "%#{params[:query]}%")
    else
      @blogs = Blog.all.reverse_order
    end
  end

  def show
    authorize(@blog)
    @blog = Blog.find(params[:id])
    # This will be used to implement metadata to the blogs
    # set_meta_tag title: @blog.title
  end

  def new
    @blog = Blog.new
    respond_to do |format|
      format.js
    end
    authorize(@blog)
  end

  def edit
    respond_to do |format|
      format.js
    end
    authorize(@blog)
  end

  def create
    @blog = Blog.new(blog_params)
    @user = current_user
    @blog.user = @user
    authorize @blog
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def update
    authorize(@blog)
    @blog.update(blog_params)
    if @blog.save
      redirect_to blogs_path(@blog)
    else
      render :edit
    end
  end

  def destroy
    authorize(@blog)
    @blog.destroy
    redirect_to blogs_url
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_latest_blog
    @latest_blogs = Blog.order(:created_at).reverse_order.limit(5)
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :subject, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :plug, :podcast, :about, :pace]

  def home
  end

  def plug
    render template: "pages/plug"
  end

  def podcast
    render template: "pages/podcast"
  end

  def about
    render template: "pages/about"
  end

  def pace
    render template: "pages/pace"
  end

  # def dashboard
  #   render template: "pages/dashboard"
  #   @user = User.all
  # end

  # def rankings
  #   render template: "pages/rankings"
  # end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_ranking, only: %i[show edit update destroy]
  def index
    @ranking = policy_scope(Ranking).last
    # @ranking = Ranking.first
  end

  def show
  end

  def new
    @ranking = Ranking.new
    authorize(@ranking)
  end

  def create
    @ranking = Ranking.new(ranking_params)
    @user = current_user
    authorize @ranking
    @ranking.save
    redirect_to rankings_url
  end

  def edit
    authorize(@ranking)
  end

  def update
    authorize(@ranking)
    @ranking.update(ranking_params)
    @ranking.save
    redirect_to rankings_url
  end

  def destroy
    authorize(@ranking)
    @ranking.destroy
    redirect_to rankings_url
  end
end

private

  def set_ranking
    @ranking = Ranking.find(params[:id])
  end

def ranking_params
  params.require(:ranking).permit(:weekly_data)
end

app/controllers/youtube_sessions_controller.rb
require 'google/api_client/client_secrets'

class YoutubeSessionsController < ApplicationController
skip_after_action :verify_authorized
skip_before_action :authenticate_user!, only: %i[new callback auth_client redirect_uri]
  def new
    @youtube_session = YoutubeSession.new
    authorize(@youtube_session)
    redirect_to auth_client.authorization_uri.to_s
  end

  def callback
    auth_client.code = params[:code]
    auth_client.fetch_access_token!
    auth_client.client_secret = nil
    # session[:credentials] = auth_client.to_json
    YoutubeSession.create!(
      credentials: auth_client
    )
    redirect_to '/'
  end

  def auth_client
    @auth_client ||= begin
      client_secrets = Google::APIClient::ClientSecrets.new(
        {
          "web": {
            "client_id": Rails.application.credentials.dig(:youtube, :client_id),
            "project_id": "clock-management-309110",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": Rails.application.credentials.dig(:youtube, :client_secret),
            "redirect_uris": [
              redirect_uri
            ]
          }
        }
      )
      auth_client = client_secrets.to_authorization
      auth_client.update!(
        scope: 'https://www.googleapis.com/auth/youtube.force-ssl',
        redirect_uri: redirect_uri,
        additional_parameters: {
          access_type: 'offline',
          include_granted_scopes: true
        }
      )
      auth_client
    end
  end

  def redirect_uri
    'http://localhost:3000/youtube_sessions/callback'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/youtube_sessions_helper.rb
module YoutubeSessionsHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for @blog do |f| %>
  <%= f.input :title %>
  <%= f.input :subject %>
  <%= f.input :body, as: :text %>
  <label class='btn btn-danger btn-sm'>
    <i class='fas fa-image'></i> Add photo
    <span style='display:none'>
      <%= f.input :photo, as: :file %>
    </span>
  </label>
  <div class="d-flex">
    <%= f.submit "submit", class:'btn btn-danger w-100' %>
  </div>
<% end %>

app/views/blogs/edit.js.erb
$('#editArticleModal').modal('show')

document.querySelector(".modal-body").innerHTML = "<%= j render 'form', blog: @blog %>"

app/views/blogs/index.html.erb
<div class="p-2 p-lg-5 p-md-3 p-sm-3 blog-list">
  <div class="row">

    <%# left side %>
    <div class="col-sm-12 col-md-8">

    <%# search bar  %>
      <div class="d-flex">
        <%= form_tag blogs_path, class: "py-2 mb-3 w-100", method: :get do %>
            <label for="blogs-input"><small class="text-danger">Looking for something in particular?</small></label>
            <div class="d-flex w-100">
              <div class="d-flex input-search-box w-100">
                <%= text_field_tag :query,
                  params[:query],
                  id: "blogs-input",
                  class: "form-control search-input",
                  placeholder: "Find article"
                %>
                <%= button_tag(type: 'submit', class: "text-danger seach-icon") do %>
                <i class="fas fa-search"></i>
                <% end %>
              </div>
              <% if user_signed_in? %>
                <% if current_user.admin || current_user.blogger %>
                  <div class="btn-box-index d-flex justify-content-center">
                   <%= link_to "Add Article", new_blog_path, remote: true, class: 'btn btn-danger btn-sm' %>
                  </div>
                <% end %>
              <% end %>
            </div>
        <% end %>
      </div>

      <% @blogs.each do |blog| %>
        <div class="d-flex border-index py-3 align-items-center">
          <%= cl_image_tag blog.photo.key, class:'img-index-card' %>
          <div class="post-details pl-3">
            <div class="text-color-small d-flex">
              <p class="py-0 m-0 pr-1"><small><strong><%= blog.subject.upcase %></strong></small></p>
              <p class="p-0 m-0"><small><%= time_ago_in_words(blog.created_at) %> ago</small></p>
            </div>
            <%= link_to blog_path(blog) do  %>
              <h5><strong><%= blog.title %></strong></h5>
            <% end %>
            <p class="body-index-card"><%= truncate(blog.body, length: 120) %><%= link_to 'Read more', blog_path(blog) %></p>
          </div>
        </div>
      <% end %>
    </div>

    <%# right side %>
    <div class="col-sm-12 col-md-4">
    <div class="sticky-col mt-4">
    <h4 class="border-index pb-2 pt-3 "><span class="text-light"><small>RECENT POSTS</small></span></h4>
      <% @latest_blogs.each do |blog| %>
        <div class="my-5 align-items-center">
          <div class="post-details pl-3">
            <div class="text-color-small d-flex mt-sm-3">
              <p class="py-0 m-0 pr-1"><small><strong><%= blog.subject.upcase %></strong></small></p>
              <p class="p-0 m-0"><small><%= time_ago_in_words(blog.created_at) %> ago</small></p>
            </div>
            <%= link_to blog_path(blog) do  %>
              <h5><strong><%= blog.title %></strong></h5>
            <% end %>
            <p class="body-index-card"><%= truncate(blog.body, length: 120) %><%= link_to 'Read more', blog_path(blog) %></p>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>


<%# CREATE NEW MODAL  %>
<div class="modal fade" id="newArticleModal" tabindex="-1" role="dialog" aria-labelledby="newArticleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-style bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" id="newArticleModalLabel">Create new article</h5>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/blogs/new.js.erb
$('#newArticleModal').modal('show')

document.querySelector(".modal-body").innerHTML = "<%= j render 'form', blog: @blog %>"

app/views/blogs/show.html.erb
<div class="p-2 p-lg-5 p-md-3 p-sm-3 blog-list">
  <div class="row">
    <div class="col-sm-12 col-md-8 mt-5">
      <div class="d-flex w-100 justify-content-between align-items-center">
        <p class="bg-danger text-light d-inline border-rounded px-2 my-2"><small><strong><%= @blog.subject.upcase %></strong></small></p>

        <% if user_signed_in? %>
          <% if current_user.admin || current_user.blogger %>
            <div class="d-flex mr-3 edit-delete-article">
              <%= link_to edit_blog_path(@blog), remote: true do %>
                <p class="p-0 m-0 text-danger mr-2"><small>Edit</small></p>
              <% end %>
              <%= link_to blog_path(@blog), method: 'delete', data: {confirm: "Are you sure?"} do %>
                <p class="p-0 m-0 text-danger"><small>Delete</small></p>
              <% end %>
            </div>
          <% end %>
        <% end %>

      </div>
      <p class="pt-3 time-ago-show"><small>Published <%= time_ago_in_words(@blog.created_at) %> ago</small></p>
      <h1 class="text-light py-3"><%= @blog.title %></h1>
        <div class="w-100">
          <%= cl_image_tag @blog.photo.key, class:'img-show wrap-image-text' %>
        <div class="text-wrap p-2">
          <p class="body-show mt-lg-0 pt-lg-0"><%= @blog.body %></p>
        </div>
      </div>
    </div>

       <%# right side %>
    <div class="col-sm-12 col-md-4">
      <div class="sticky-col mt-4">
      <h4 class="border-index pb-2 pt-3 "><span class="text-light"><small>RECENT POST</small></span></h4>
        <% @latest_blogs.each do |blog| %>
          <div class="my-5 align-items-center">
            <div class="post-details pl-3">
              <div class="text-color-small d-flex mt-sm-3">
                <p class="py-0 m-0 pr-1"><small><strong><%= blog.subject.upcase %></strong></small></p>
                <p class="p-0 m-0"><small><%= time_ago_in_words(blog.created_at) %> ago</small></p>
              </div>
              <%= link_to blog_path(blog) do  %>
                <h5><strong><%= blog.title %></strong></h5>
              <% end %>
              <p class="body-index-card"><%= truncate(blog.body, length: 120) %><%= link_to 'Read more', blog_path(blog) %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<%# EDIT MODAL  %>
<div class="modal fade" id="editArticleModal" tabindex="-1" role="dialog" aria-labelledby="editArticleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-style bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" id="editArticleModalLabel">Create new article</h5>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- link to icon -->
    <%= favicon_link_tag %>

    <title>Clock Management - U.S. Army Veteran and fantasy
      football analyst</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Clock Management Fantasy Football analyst and United States Army Veteran">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name=”robots” content="index, follow">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/da08ff94e5.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <main style="min-height: 70vh;">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

</html>

app/views/pages/about.html.erb
<div class="bg-dark about">
  <div class="container">
    <h1 class="h1-text text-center">About Us</h1>
    <p class="">Want to win your fantasy football league? Well, you have come to the right place! Justin and Perry are top analysts in the country. They compete every year on accuracy rankings with all the top names in the industry, and have appeared alongside of NFL Network personalities Marcas Grant, and Michael F. Florio as well as CBS analyst Heath Cummings to name a few. Clock Management believes in giving back to our viewership and does monthly autographed jersey giveaways of top fantasy players!
    <br> <br>
    Justin is an Active duty soldier in the U.S. Army and has been playing fantasy football for over a decade. He has appeared on several networks such as Warzone Sports Network, Rumboyz Sports Network, GMM Network and others. He is part of the FantasyPros Expert rankings program and his favorite prediction was the Tyreek Hill breakout year.</p>
  </div>
  <div class="about-pics">
    <image>
      <%= image_tag('justin-pic.jpg', height: '40%', width: '25%') %>
      <%= image_tag('perry.jpg', height: '40%', width: '25%') %>
  </image>
  </div>
</div>

app/views/pages/dashboard.html.erb
<!-- <h1>lkjlkj</h1>

<% @user.each do |user| %>
  <%= user.email %>
<% end %>
 -->

app/views/pages/home.html.erb
<div class="home-header d-flex align-items-center">
    <div class="container home-banner-content justify-content-center">
      <div class="row w-100 justify-content-center">
        <%= link_to "Join our mailing list for a chance to win exclusive prizes!", new_user_registration_path, :method => :get, class: 'btn btn-dark nav-link text-center mt-3' %>
        <div class="header-content col-sm-12 col-md-6 justify-content-center">
          <h1 class="mt-5">Welcome to Clock <br>Management</h1>
          <p>U.S. Army Veteran and Fantasy <br> Football Analyst</p>
          <%= link_to "CHECK OUT OUR PODCAST", 'https://www.youtube.com/channel/UCvyxe3D80SlsfTrz3rJTsAQ', target: '_blank', class: "btn btn-danger mt-3 mb-5" %>
        </div>
        <div class="video-intro col-sm-12 col-md-6 d-flex align-items-center" controlsList="nodownload">
          <iframe style="border-radius: 10px; box-shadow: 2px 2px 10px #DE3932;" src="https://www.youtube.com/embed?listType=playlist&list=PLI3iJ77cGNJV_YqYyAPCEgSvpyR61zdZJ" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
  </div>
</div>

app/views/pages/pace.html.erb
<div class="bg-dark">
  <div class="container">
    <h1 class="h1-text text-center">P.A.C.E</h1>
    <%#= image_tag "pacelogo.jpg", alt: "This is the logo for the P.A.C.E", width: 200; %> <br>
    <div class="pace">
    The Plug And Clock Experience (P.A.C.E.) is a fantasy football league made to raise money for several charities. Each member chooses a charity to represent and the money raised goes to the winner of the league’s chosen charity. You can donate
      <a href="https://www.spotfund.com/story/586a7fef-2cdb-45d1-9245-3227a08f28b3?fbclid=IwAR1fTiP0FbFuzcxXKxt4ZZDuS9EYkduYX5V6XW9EfOcwkvrF6Xmg4rc8ovM#" target="__blank">here</a>.
      We also do a weekly podcast based on this league welcoming on the different members. Below is the list of members: <br>
      <div class="pace-content">
        <div>
          <ul>
            <li>
              T-Pain
            </li>
            <li>
              Darren Waller
            </li>
            <li>
              Coach Hue Jackson
            </li>
            <li>
              Danny Woodhead
            </li>
            <li>
              Young Cash
            </li>
            <li>
              Andy Holloway (The Fantasy Footballers)
            </li>
            <li>
              Marcas Grant (NFL)
            </li>
            <li>
              Michael F. Florio (NFL)
            </li>
            <li>
              Bogard (The GMM Network)
            </li>
            <li>
              Bear Clothing
            </li>
            <li>
              Fantasy Couch
            </li>
            <li>
              Smitty (the Fantasy Football Show)
            </li>
          </ul>
        </div>
        <div>
          <%= image_tag "pacelogo.jpg", alt: "P.A.C.E speakers", class: "pace-photo" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/plug.html.erb
<title>Plugged in with Jay - Interviews with some great people. As well as Fantasy Football Advice </title>
<div class="container video-container">
    <h1 class="h1-text text-center">Plug's Interviews</h1>
    <iframe id="ytplayer" type="text/html"
      src="https://www.youtube.com/embed?listType=playlist&list=PLbYTyHsuIhBQbOD6KDnlVPHQhJm8f9N9g"
      frameborder="0"></iframe>
</div>

<script>
  // Load the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // Replace the 'ytplayer' element with an <iframe> and
  // YouTube player after the API code downloads.
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('ytplayer', {
      // height: '360',
      // width: '640',
      videoId: 'M7lc1UVf-VE'
    });
  }
</script>

app/views/pages/podcast.html.erb
<title>US Army veteran run fantast football podcast</title>
<div class="container video-container">
  <h1 class="h1-text text-center">Clock Management Podcast</h1>
  <iframe id="ytplayer" type="text/html"
    src="https://www.youtube.com/embed?listType=playlist&list=PLI3iJ77cGNJV_YqYyAPCEgSvpyR61zdZJ"
    frameborder="0">
  </iframe>
</div>

<script>
  // Load the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // Replace the 'ytplayer' element with an <iframe> and
  // YouTube player after the API code downloads.
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('ytplayer', {
      // height: '360',
      // width: '640',
      videoId: 'M7lc1UVf-VE'
      listType: 'user_uploads'
    });
  }
</script>

app/views/rankings/index.html.erb
<title>Weekly expert Fantasy football rankings</title>
<div class="container mb-5 text-info" id="ranking-container">
    <h1 class="text-center">Clock Management Rankings</h1>

    <% if user_signed_in? %>
      <% if current_user.admin %>
        <%= simple_form_for @ranking do |f| %>
            <%= f.label :weekly_data, "Publish here:"%>
            <%= f.input :weekly_data, as: :text, label: false, placeholder: "Update here weekly rankings" %>
            <%= f.submit "Publish" %>
          <% end %>
      <% end %>
    <% end %>

    <div>
      <%= @ranking.weekly_data.try(:html_safe) %>
</div>

app/views/shared/_flashes.html.erb
  <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container footer-wrapper">
    <div class="copyright">© 2021 Clock Management. All rights reserved.</div>
    <div class="footer-icons d-flex justify-content-center">
      <%= link_to"https://www.youtube.com/channel/UCvyxe3D80SlsfTrz3rJTsAQ" do %>
        <i class="fab fa-youtube"></i>
      <% end %>
      <%= link_to"https://open.spotify.com/show/3KdIcHtyauW8QSBX10D6YQ?si=1oBHN9D3TVKQ8D1eqbzppg&utm_source=copy-link&fbclid=IwAR1IYDM3Xr5ty386LhQSfG85Tr7_fKh1mKiDSC89a0MRgVG-B3PFmxgawVo&nd=1" do %>
        <i class="fab fa-spotify"></i>
      <% end %>
      <%= link_to"https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9jOTk4MDg0L3BvZGNhc3QvcnNz" do %>
        <i class="fab fa-google"></i>
      <% end %>
      <%= link_to"https://podcasts.apple.com/us/podcast/clock-management/id1472955303?uo=4" do %>
        <i class="fab fa-itunes"></i>
      <% end %>
      <%= link_to new_user_session_path do %>
        <i class="fas fa-football-ball"></i>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-custom bg-dark navie">

      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag("clockm1.png", height: '100', class: 'nav-pic') %>
      <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span><i class="fas fa-bars text-danger"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link active text-danger" aria-current="page" href="/pages/podcast">PODCAST</a>
        </li>
        <li class="nav-item">
          <%= link_to "ARTICLES", blogs_path, class: 'nav-link text-danger' %>
        </li>
        <li class="nav-item">
          <%= link_to "RANKINGS", rankings_path, class: 'nav-link text-danger' %>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-danger" aria-current="page" href="/pages/plug">PLUG'S INTERVIEWS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-danger" aria-current="page" href="/pages/pace">P.A.C.E</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-danger" aria-current="page" href="/pages/about">ABOUT</a>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <% if  current_user.admin %>
              <%= link_to "GOD MODE", rails_admin_path, class: 'nav-link text-danger' %>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "LOG OUT", destroy_user_session_path, :method => :delete, class: 'nav-link text-danger' %>
          <% end %>
        </li>
        <!-- <li class="nav-item">
          <% if ! user_signed_in? %>
            <%= link_to "LOGIN", new_user_session_path, :method => :get, class: 'nav-link text-danger' %>
          <% end %>
        </li> -->
      </ul>
    </div>

</nav>